version: '3'
services:
    nginx:
        container_name: product-nginx
        build:
            context: .
            dockerfile: nginx/dockerfile
        image: 'collectandverything-nginx'
        restart: unless-stopped
        tty: true
        volumes:
            - './conf/nginx/nginx.conf:/etc/nginx/nginx.conf'
        networks:
            - app-network
    php-fpm:
        container_name: product-php
        #env_file: '.env'
        build:
            context: .
              #args:
            #- GITLAB_BRANCH=${CI_COMMIT_BRANCH}
            dockerfile: php/dockerfile
        volumes:
            - './:/var/www'
        image: 'collectandverything-product:latest'
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        networks:
            - app-network
networks:
    app-network:
        external:
            name: collectandverything
